sudo: required
dist: trusty

services:
  - docker

language: node_js
matrix:
  include:
  - node_js: "4.7"
    env: LINT=0
  - node_js: "6.9"
    env: LINT=0
  - node_js: "7.4"
    env: LINT=1

notifications:
  email: false

script:
  - docker run -d --name mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_DATABASE=test -p 33306:3306 mysql:5.7
  - docker run --link mysql:db -e CHECK_PORT=3306 -e CHECK_HOST=db giorgos/takis
  - node --version
  - npm --version
  - if [ "$LINT" = "1" ]; then npm run lint; fi
  - MYSQL_PORT=33306 npm run test:raw
